
on:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write

jobs:
  hosted-backend-build:
      runs-on: ubuntu-latest
      environment: ALL
      permissions:
        id-token: write
        contents: read
      steps:
        - name: Docker login to ACR
          run: echo $GITHUB_REF