
on:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write

jobs:
  hosted-backend-build:
    if: contains(github.event.release.tag_name, 'dashboard-backend')
    runs-on: ubuntu-latest
    environment: ALL
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Docker login to ACR
        run: echo $GITHUB_REF