name: Validate PR title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main
      - '!release-please--branches--master--components--**'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            perf
            revert
            docs
            style
            refactor
            test
            build
            ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
