name: ExampleWorkflow
on:  
  pull_request:
    types: [labeled]
    branches:
      - main
jobs:
  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          all_of: 'autorelease: pending,notify-to-slack'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          allow_failure: true

  notify-to-slack:
    # if: contains(github.event.pull_request.labels.*.name, 'notify-to-slack') && contains(github.event.pull_request.labels.*.name, 'autorelease')
    runs-on: ubuntu-latest
    steps:
      - uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://ricardoaccount2000.app.n8n.cloud/webhook-test/21657086-0cfc-41f9-ae89-9aff434e39cf'
          method: 'POST'
          data: ${{ github.event }}